## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# Setups
format="$directory$git_branch$character"
right_format = """$git_status$cmd_duration"""
add_newline = true

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true

[conda]
format = ' [$symbol$environment](dimmed green) '

# Prompt symbols 
[character]
success_symbol = "[](#458588 bold)"
error_symbol = "[](#cc241d)"
vicmd_symbol = "[](#f6c177)"

[directory]
format = "[]($style)[ ](bg:#d79921 fg:#282828)[$path](bg:#d79921 fg:#ebdbb2 bold)[ ]($style)"
style = "bg:none fg:#d79921"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[]($style)[[ ](bg:#3c3836 fg:#b8bb26 bold)$branch](bg:#3c3836 fg:#b8bb26)[ ]($style)"
style = "bg:none fg:#3c3836"

[git_status]
# $all status$ahead_behind
format = "[]($style)[$all_status$ahead_behind](bg:#3c3836 fg:#ebdbb2)[ ]($style)"
style = "bg:none fg:#3c3836"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[󰔚 ](bg:#3c3836 fg:#fb4934 bold)$duration](bg:#3c3836 fg:#ebdbb2)[ ]($style)"
disabled = false
style = "bg:none fg:#3c3836"
